import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import Navbar from './components/Navbar';
import { QueryClientProviderCmp } from '../providers/QueryclientProviderCmp';
import './global.css';

export const metadata = {
  title: 'Welcome to user-frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProviderCmp>
          <Navbar />
          {children}
        </QueryClientProviderCmp>
      </body>
    </html>
  );
}
